### ISSUE TITLE
Unrecoverable error in TUI install using all default choices

### ISSUE THREAD

**Issue by ydirson** [xenserver/host-installer#65] opened 2023-09-27 08:38 UTC
When making an install with v10.10.8 and selecting all default choices in the TUI, during installation the user is presented with a `'NoneType' object is not iterable` error and can only reboot.

The log shows it happens in `rewriteNTPConf` while attempting to iterate on `ntp_servers`.

Cannot guess the source while just looking at the NTP rework patch, and cannot bisect it either: that big commit doing several things demonstrates the value of splitting into individual commits (eg. "Replace time-config-method with ntp-config-method to prepare for DHCP support", "Separate NTP servers manual selection into a separate dialog", "Introduce option to get NTP servers from DHCP", and likely more that whose need would naturally arise as separate from those 3 main topics during careful review if the patches).

Likely linked with #64.

**Comment by alexbrett** [comment] 2023-09-27 09:05
I believe this is fixed by https://github.com/xenserver/host-installer/commit/a9a5901a343311130c5cfbe20c477fa61f2f88ad

**Comment by ydirson** [comment] 2023-09-27 09:14
Right, I just stumbled on it, by diffing the source in the latest xs8 install ISO.

**Comment by ydirson** [comment] 2023-09-27 09:15
Doesn't that makes #62 a good idea? ;)

**Comment by ydirson** [comment] 2023-09-27 09:19
Still, I would have valued an explanation in the fix commit, explaining why this can be None.  Everywhere in the code `answers['ntp-servers']` seems to be assigned an iterable value: this additional check seems to just be hiding the source of the problem rather than fixing it.

**Comment by GeraldEV** [comment] 2023-10-02 13:38
Apologies, this was fixed/worked-around in a rush to meet a deadline, it was resolved in this PR https://github.com/xenserver/host-installer/pull/60/files
I've not yet had time to investigate the root cause - as observed the paths through the installer would seem to set it properly and yet the issue still occurred

**Closed by GeraldEV** 2023-10-02 13:38 UTC

**Comment by ydirson** [comment] 2023-10-02 13:46
> I've not yet had time to investigate the root cause - as observed the paths through the installer would seem to set it properly and yet the issue still occurred

Yes, as it is, it is not easy to test changes. We should really put our thoughts towards getting automated tests on this codebase.

Note I have a done some time ago a prototype that allows to [manually test UI changes](https://github.com/xcp-ng/host-installer/commit/77df3217ce6c25dfa0c3ae4d0e25e1c5fea13def) by running some of the code locally (told @bernhardkaindl about that). Certainly limited and not suited to running automatically - just ideas.
